apiVersion: apps/v1
kind: StatefulSet
metadata: {name: postgres}
spec:
  template:
    spec:
      nodeSelector: {workload: pro}
      tolerations:
        - {key: dr, operator: Exists, effect: NoSchedule}
