import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,existsSync,statSync,rmSync,mkdirSync,chmodSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const script=fileURLToPath(new URL('../scripts/prepare-k8s-env.mjs',import.meta.url));
const root=mkdtempSync(join(tmpdir(),'connectme-k8s-test-'));
const read=(dir,file)=>readFileSync(join(dir,file),'utf8');
function run(cwd,args,expected=0){
 const r=spawnSync(process.execPath,[script,...args],{cwd,encoding:'utf8'});
 assert.equal(r.status,expected,r.stderr);
 return r.stdout+r.stderr;
}
try{
 run(root,[],1);run(root,['invalid'],1);run(root,['dev','--check'],1);
 assert.equal(existsSync(join(root,'.local')),false,'check must not create files');
 const log=run(root,['dev']);
 const dir=join(root,'.local/kubernetes/dev');
 const env=read(dir,'runtime.env'),raw=read(dir,'bootstrap.yaml'),doc=JSON.parse(raw);
 assert.equal(doc.kind,'List');assert.equal(doc.items.length,2);
 assert.equal(doc.items[0].metadata.name,'connectme-dev');
 const secret=doc.items[1];assert.equal(secret.metadata.namespace,'connectme-dev');assert.equal(secret.metadata.name,'connectme-runtime');
 const values=Object.fromEntries(Object.entries(secret.data).map(([k,v])=>[k,Buffer.from(v,'base64').toString()]));
 assert.equal(decodeURIComponent(new URL(values.CONNECTME_DATABASE_URL).password),values.POSTGRES_PASSWORD);
 for(const key of ['CONNECTME_MASTER_KEY','CONNECTME_AUDIT_HMAC_KEY'])assert.equal(Buffer.from(values[key],'base64').length,32);
 assert.equal(values.CONNECTME_COOKIE_SECURE,'true');
 assert.equal(log.includes(values.POSTGRES_PASSWORD),false);
 assert.equal(log.includes(values.CONNECTME_MASTER_KEY),false);
 assert.equal(statSync(join(dir,'runtime.env')).mode&0o777,0o600);
 assert.equal(statSync(join(dir,'bootstrap.yaml')).mode&0o777,0o600);
 assert.equal(statSync(dir).mode&0o777,0o700);
 run(root,['dev']);run(root,['dev','--check']);
 assert.equal(read(dir,'runtime.env'),env);assert.equal(read(dir,'bootstrap.yaml'),raw);
 run(root,['pro']);
 const pro=JSON.parse(read(join(root,'.local/kubernetes/pro'),'bootstrap.yaml')).items[1];
 assert.equal(pro.metadata.namespace,'connectme-pro');
 assert.notEqual(pro.data.CONNECTME_MASTER_KEY,secret.data.CONNECTME_MASTER_KEY);
 assert.equal(Buffer.from(pro.data.CONNECTME_ENV,'base64').toString(),'production');
 chmodSync(join(dir,'runtime.env'),0o644);run(root,['dev','--check'],1);run(root,['dev']);
 assert.equal(statSync(join(dir,'runtime.env')).mode&0o777,0o600);
 writeFileSync(join(dir,'bootstrap.yaml'),'{}');run(root,['dev'],1);
 assert.equal(read(dir,'runtime.env'),env);
 writeFileSync(join(dir,'bootstrap.yaml'),raw);
 rmSync(join(dir,'runtime.env'));run(root,['dev'],1);
 assert.equal(read(dir,'bootstrap.yaml'),raw,'orphan manifest must not be replaced');
 const imported=join(root,'imported');mkdirSync(imported);
 const original=join(root,'original.env');writeFileSync(original,env,{mode:0o600});
 run(imported,['dev','--from',original]);
 assert.equal(read(join(imported,'.local/kubernetes/dev'),'runtime.env'),env);
 run(imported,['dev','--from',join(root,'.local/kubernetes/pro/runtime.env')],1);
 const legacy=join(root,'legacy');mkdirSync(join(legacy,'.local'),{recursive:true});
 writeFileSync(join(legacy,'.local/connectme-dev.env'),env,{mode:0o600});
 run(legacy,['dev']);assert.equal(read(join(legacy,'.local/kubernetes/dev'),'runtime.env'),env);
 const invalid=join(root,'invalid');mkdirSync(invalid);
 writeFileSync(join(root,'bad.env'),env.replace(/^POSTGRES_PASSWORD=.*$/m,'POSTGRES_PASSWORD=different'));
 run(invalid,['dev','--from',join(root,'bad.env')],1);
 assert.equal(existsSync(join(invalid,'.local/kubernetes/dev/runtime.env')),false);
 const linked=join(root,'linked');mkdirSync(linked);symlinkSync(join(imported,'.local'),join(linked,'.local'));
 run(linked,['dev'],1);
 console.log('PASS: fresh dev/pro, namespaces, random independent keys, permissions, no secret output, idempotency, import/legacy preservation, mismatch and symlink protection');
}finally{rmSync(root,{recursive:true,force:true})}
