apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connectme-dev
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
patches:
  - path: scheduling.yaml
  - path: postgres-scheduling.yaml
images:
  - name: virgiliofilhos/connectme-server
    newTag: dev
