'use strict';
const $=id=>document.getElementById(id),notice=$('notice');
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('connectme_csrf='))?.split('=')[1]||''}
async function api(path,method='GET',body){const r=await fetch('/api/v1/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf()},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401){location.href='/';throw Error('Sessão expirada')}const data=r.status===204?{}:await r.json();if(!r.ok)throw Error(data.error?.detail||'Operação recusada');return data}
function fail(e){notice.textContent=e.message;const inline=$('editor-feedback');if(inline){inline.textContent=e.message;inline.scrollIntoView({block:'nearest'})}}
document.addEventListener('invalid',e=>{if(e.target.closest('#editor'))fail(Error(e.target.name==='password'?'A senha deve ter pelo menos 12 caracteres.':e.target.validationMessage))},true);
$('logout').onclick=()=>api('auth/logout','POST',{}).then(()=>location.href='/').catch(fail);
$('password').onsubmit=async e=>{e.preventDefault();try{await api('auth/password','POST',Object.fromEntries(new FormData(e.target)));location.href='/'}catch(err){fail(err)}};
const defs={
 locations:{label:'Localizações',fields:[['name','Nome'],['region','Região'],['description','Descrição']],cols:['name','region','enabled']},
 networks:{label:'Redes',fields:[['location_id','Localização','locations'],['name','Nome'],['cidr','CIDR']],cols:['name','cidr','enabled']},
 hosts:{label:'Hosts',fields:[['location_id','Localização','locations'],['name','Nome'],['address','IP ou hostname'],['operating_system','Sistema','linux|windows|other'],['description','Descrição']],cols:['name','address','operating_system','enabled']},
 credentials:{label:'Credenciais',fields:[['name','Nome'],['type','Tipo','password|ssh-key|windows'],['username','Utilizador remoto'],['domain','Domínio Windows (opcional)'],['value','Senha/chave (vazio ao editar mantém atual)','secret']],cols:['name','type','username','domain','enabled']},
 connections:{label:'Conexões',fields:[['name','Nome'],['host_id','Host','hosts'],['credential_ref_id','Credencial','credentials'],['protocol','Protocolo','rdp|ssh|vnc'],['port','Porta','number'],['clipboard_copy_enabled','Copiar texto do remoto','false|true'],['clipboard_paste_enabled','Colar texto no remoto','false|true'],['file_upload_enabled','Enviar arquivos ao remoto','false|true'],['file_download_enabled','Baixar arquivos do remoto','false|true']],cols:['name','protocol','port','enabled']},
 users:{label:'Utilizadores',fields:[['email','Utilizador/email'],['display_name','Nome'],['password','Senha (mínimo 12)','password']],cols:['email','display_name','enabled','mfa_enabled']}
};
let current='locations',offset=0,generation=0,editing=null,items=[];
async function options(kind){let result=[];for(let pos=0;;pos+=200){const d=await api(kind+'?limit=200&offset='+pos);const rows=d.items||[];result.push(...rows);if(rows.length<200)break}return result}
async function form(item=null){editing=item;const gen=++generation;const d=defs[current];$('editor').replaceChildren();$('cancel').hidden=!item;$('heading').textContent=(item?'Editar ':'Criar ')+d.label;for(const [name,label,type] of d.fields){const wrap=document.createElement('label');wrap.textContent=label;let el;if(['locations','hosts','credentials'].includes(type)||type?.includes('|')){el=document.createElement('select');const values=type.includes('|')?type.split('|').map(v=>({id:v,name:v})):await options(type);if(gen!==generation)return;for(const v of values){const o=document.createElement('option');o.value=v.id;o.textContent=v.name+(v.enabled===false?' (bloqueado)':'');el.append(o)}}else{el=document.createElement('input');el.type=type==='secret'?'password':type||'text';if(type==='secret'||type==='password'){el.autocomplete='new-password';el.spellcheck=false;el.autocapitalize='none'}if(type==='secret'){const picker=document.createElement('input');picker.type='file';picker.setAttribute('aria-label','Importar chave privada sem exibir conteúdo');picker.onchange=async()=>{const file=picker.files[0];if(!file)return;if(file.size>65536){picker.value='';fail(Error('Chave limitada a 64 KiB.'));return}el.secretValue=await file.text();el.value='chave importada';picker.value=''};el.oninput=()=>{delete el.secretValue};wrap.append(picker)}if(name==='password')el.minLength=12;if(type==='number'){el.min=1;el.max=65535}}el.name=name;el.required=!['region','description','domain','username'].includes(name)&&!(['value','password'].includes(name)&&item);if(item&&item[name]!=null)el.value=item[name];else if(name==='port')el.value=3389;wrap.append(el);$('editor').append(wrap)}if(item){const label=document.createElement('label');label.textContent='Estado';const select=document.createElement('select');select.name='enabled';for(const [v,n] of [['true','Ativo'],['false','Bloqueado']]){const o=document.createElement('option');o.value=v;o.textContent=n;select.append(o)}select.value=String(item.enabled!==false);label.append(select);$('editor').append(label)}const save=document.createElement('button');save.type='submit';save.textContent=item?'Salvar alterações':'Criar';$('editor').append(save);const feedback=document.createElement('p');feedback.id='editor-feedback';feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');$('editor').append(feedback)}
async function choose(key){current=key;offset=0;notice.textContent='';for(const b of document.querySelectorAll('nav button'))b.setAttribute('aria-current',String(b.dataset.key===key));await form();await reload()}
function action(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){fail(e)}finally{b.disabled=false}};return b}
async function reload(){const key=current;const d=await api(key+'?limit=50&offset='+offset);if(key!==current)return;items=d.items||[];$('rows').replaceChildren();$('columns').replaceChildren();const tr=document.createElement('tr');for(const col of [...defs[key].cols,'Ações']){const th=document.createElement('th');th.textContent=col;tr.append(th)}$('columns').append(tr);for(const item of items){const row=document.createElement('tr');for(const col of defs[key].cols){const td=document.createElement('td');td.textContent=String(item[col]??'');row.append(td)}const actions=document.createElement('td');if(true){actions.append(action('Editar',()=>form(item)));actions.append(action('Remover',async()=>{if(!confirm('Remover '+(item.name||item.display_name)+'? O registro será desativado e ocultado.'))return;await api(key+'/'+item.id,'DELETE');await form();await reload()}))}if(key==='connections'){if(item.protocol==='rdp'||item.protocol==='ssh')actions.append(action('Abrir',async()=>{await openDesktop(item)}));else{const pending=document.createElement('span');pending.textContent=item.protocol.toUpperCase()+' — execução ainda indisponível';actions.append(pending)}}row.append(actions);$('rows').append(row)}$('paging').textContent=items.length+' registros · posição '+offset;$('previous').disabled=offset===0;$('next').disabled=key==='users'||items.length<50}
if($('editor')){for(const [key,d] of Object.entries(defs)){const b=action(d.label,()=>choose(key));b.dataset.key=key;$('navigation').append(b)}$('cancel').onclick=()=>form().catch(fail);$('refresh').onclick=()=>reload().catch(fail);$('previous').onclick=()=>{offset=Math.max(0,offset-50);reload().catch(fail)};$('next').onclick=()=>{offset+=50;reload().catch(fail)};$('editor').onsubmit=async e=>{e.preventDefault();const save=$('editor').querySelector('button');save.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));const secret=e.target.elements.namedItem('value');if(secret?.secretValue!==undefined)body.value=secret.secretValue;let path=current,method='POST';if(editing){path+='/'+editing.id;method='PUT';body.enabled=body.enabled==='true';if(current==='connections'){}}if(current==='networks'&&!editing){path='locations/'+body.location_id+'/networks';delete body.location_id}if(current==='connections'){body.port=Number(body.port);for(const flag of ['clipboard_copy_enabled','clipboard_paste_enabled','file_upload_enabled','file_download_enabled'])body[flag]=body[flag]==='true';body.clipboard_enabled=body.clipboard_copy_enabled||body.clipboard_paste_enabled;body.file_transfer_enabled=body.file_upload_enabled||body.file_download_enabled}await api(path,method,body);notice.textContent='Alterações salvas.';await form();$('editor-feedback').textContent='Alterações salvas.';await reload()}catch(err){fail(err)}finally{save.disabled=false}};choose(current).catch(fail)}
